### ISSUE TITLE
Weekly Modelo a ser disparada no dia 22/01/2016

### ISSUE THREAD

**Issue by cristofersousa** [opensanca/weekly#1]
Ajude o [OpenSanca Weekly!](http://opensanca.us12.list-manage1.com/subscribe?u=594600fabbe8e704e4a101715&id=5c8823aad4) postando sua dica, link ou sugestão aqui nos comentários desta issue.
Ao longo da semana vamos debatendo e juntando os melhores links que serão inseridos na próxima Weekly.
### Template para uma boa dica (Não é obrigatório, faça como quiser):

```
  **[Título](URL)**
    Descrição curta:
   *Categoria*:
```
### Categoria

Para a categoria, escolha em qual contexto o link melhor se encaixa, alguns dos exemplos de categorias mais utilizadas:
- Artigos
- News
- Videos
- Eventos
- Tools
- Demos
- Vagas
- Outros
### Exemplo de dica:

> **[Nova versão do Node.JS lançada](http://blog.nodejs.org/2015/02/06/node-v0-12-0-stable/)**
> Descrição: Saiu o release da versão 0.12(stable) do Node.js
> _Categoria:_ News

PS: Thumbs up para quem seguir os exemplos, pois facilita MUITO a vida de quem edita a news no Mailchimp (posso só copiar e colar lá).

**Comment by fczuardi** [comment]
**[React Europe](https://www.youtube.com/channel/UCorlLn2oZfgOJ-FUcF2eZ1A/playlists)**
    Descrição curta: React Europa Tour
   _Categoria_: Videos

**Comment by korzzus** [comment]
@fczuardi  estarei montando a weekly para teste na próxima semana, mas peço por gentileza  para que possamos elaborar ela com mais facilidade para manter o padrão do template. ;) 

Abraços

**Comment by cristofersousa** [comment]
**[Escrevendo e publicando um livro online com github pages e gitbook](http://jotateles.com.br/dicas/2016/01/17/escrevendo-e-publicando-um-livro-online-com-github-pages-e-gitbook-parte1.html)**
    Descrição curta: Entendendo como escrever um livro usando os recursos do GitHub.
   _Categoria_: Artigos

**Comment by cristofersousa** [comment]
**[A new mobile navigation menu](https://medium.com/@supjoey/the-curtain-menu-redesigning-drop-down-navigation-for-mobile-bd63b555a3df#.965k22wbu)**
    Descrição curta: Converting the desktop dropdown nav
   _Categoria_: Artigos

**Comment by cristofersousa** [comment]
**[TokenLab está contratando - Desenvolvedor Web](http://tokenlab.com.br/)**
    Descrição curta: Experiência em desenvolvimento Web com ASP.Net, HTML, CSS, Javascript e Bootstrap
   _Categoria_: Vagas

**Comment by cristofersousa** [comment]
**[Sanca Ventures está contratando - 06 vagas em aberto ](https://www.facebook.com/photo.php?fbid=10205644197440115&set=a.2562821745721.2110504.1109404412&type=3&theater)**
    Descrição curta: Sanca Ventures está com vagas abertas para um projeto incrível de Inteligência Artificial - IA
- 1 Arquiteto de Software [Senior]
- 1 Especialista em Machine Learning [Senior]
- 3 Desenvolvedores [Pleno/Junior]
- 1 Desenvolvedor [Estagiário]

_Categoria_: Vagas

**Comment by cristofersousa** [comment]
**[Siena Idea está contratando - Freela](http://www.sienaidea.com.br)**
    Descrição curta:Temos vagas para dois freelas: um freela mobile e outro web.
   _Categoria_: Vagas

**Comment by cristofersousa** [comment]
**[Networkr  está contratando -  Desenvolvedor Web](https://networkr.recruiterbox.com/)**
    Descrição curta: Abrimos 2016 "a milhão". Estamos nos preparando para contratar. Parte boa, trabalho remoto.
   _Categoria_ : Vagas

**Comment by cristofersousa** [comment]
**[Guarani Sistemas está contratando -  Desenvolvedor Web & Mobile ](http://www.guaranisistemas.com.br/noticias/temos-vagas-para-desenvolvedor-java-web-e-android-integral-clt/)**
    Descrição curta: Estamos abrindo vagas para programadores em Java Web, Delphi e Android 
   _Categoria_: Vagas

**Comment by cristofersousa** [comment]
**[Quer tal você, ministrar um workshop no Opensanca?](http://goo.gl/forms/M6bNw5EbEA)**
    Descrição curta: Enquete aberta para palestrantes de eventos e workshops para o meetup.
   _Categoria_: Outros

**Comment by cristofersousa** [comment]
**[#2 OpenTalks  - Disruptive Nerworking](http://goo.gl/TRsLTS)**
    Descrição curta: Roda de palestras sobre Web Scraping, Design de Produto e Automação de Tarefas
   _Categoria_: Eventos

**Comment by cristofersousa** [comment]
**[Pesquisa salarial sobre mercado de TI de Araraquara ](http://goo.gl/forms/uIai8sbqfI)**
    Descrição curta: Enquete aberta para saber como está o financeiro das empresas de TI.
   _Categoria_: Outros

**Comment by cristofersousa** [comment]
**[Open Source Checklist](http://afonsopacifer.github.io/open-source-checklist/pt-br.html)**
    Descrição curta: Um guia para ajudar você a lembrar de coisas importantes na hora de criar seus projetos abertos no Github ;D
   **Categoria**: Artigos

**Comment by cristofersousa** [comment]
**[Markdown feito em Javascript](http://nextstepwebs.github.io/simplemde-markdown-editor/)**
    Descrição curta: Bom editor Markdown feito em Javascript para embutir em uma webapp.
   _Categoria_: Tools

**Comment by cristofersousa** [comment]
**[Porque você deveria utilizar NPM ao invés de Grunt ou Gulp](https://medium.com/@housecor/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8#.gylatg80s)**
    Descrição curta: Autor avalia que utiliza Grunt ou Gulp adota scripts descenessários e o NPM é mais eficaz.
   _Categoria_: Artigos

**Comment by cristofersousa** [comment]
**[Lista de Podcasts](https://github.com/ogilvieira/dev-podcast-list-brazil)**
    Descrição curta: Lista de podcasts focados em programação, tecnologia e ciências da computação.
   _Categoria_:Artigos

**Comment by cristofersousa** [comment]
**[The Clean Code Blog](http://blog.cleancoder.com/uncle-bob/2016/01/04/ALittleArchitecture.html)**
    Descrição curta: Falando um pouco sobre a guerra das linguagens de programação.
   _Categoria_: Artigos

**Comment by gcabrini** [comment]
**[Designing A Product Page Layout with Flexbox](https://css-tricks.com/designing-a-product-page-layout-with-flexbox/)**
    Descrição curta: Desenvolvimento de uma vitrine de produtos utilizando a propriedade css flexbox.
   _Categoria_: Artigos

**Comment by cristofersousa** [comment]
**[Free-Time](http://free-time.github.io/)**
    Descrição curta:Free time é um projeto open source que reúne palestras sobre desenvolvimento, UX      e startups.
   _Categoria_: News

**Comment by cristofersousa** [comment]
**[Mais de 1.000 livros sobre programação para estudar grátis (Inglês e Português)](http://suporteninja.com/mais-de-1-000-livros-sobre-programacao-para-estudar-gratis-ingles-e-portugues)**
    Descrição curta: Incentivo a estudar programação de forma gratuita.
   _Categoria_: Outros

**Comment by cristofersousa** [comment]
**[Docker Tutorial #1](https://www.youtube.com/watch?v=0cDj7citEjE)**
    Descrição curta: Docker, Containers, Images e muito mais, canal do LinuxTips abordando sobre o que mais se tem falado na comunidade!
   _Categoria_: Videos
